CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) NOT NULL,
  role VARCHAR2(20) CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE tickets (
  ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(100) NOT NULL,
  description CLOB,
  status VARCHAR2(20) DEFAULT 'OPEN',
  created_by NUMBER,
  created_at DATE DEFAULT SYSDATE,

  CONSTRAINT fk_ticket_user
    FOREIGN KEY (created_by)
    REFERENCES users(user_id)
);

CREATE TABLE ticket_history (
  history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER,
  old_status VARCHAR2(20),
  new_status VARCHAR2(20),
  changed_at DATE DEFAULT SYSDATE,

  CONSTRAINT fk_history_ticket
    FOREIGN KEY (ticket_id)
    REFERENCES tickets(ticket_id)
);
